services:
  - type: web
    name: reels-downloader-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: bash start.sh
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: INSTAGRAM_COOKIES
        sync: false
      - key: YOUTUBE_COOKIES
        sync: false
      - key: TIKTOK_COOKIES
        sync: false
      - key: TWITTER_COOKIES
        sync: false
